#!/usr/bin/env bash
# Capture the REAL Deck's userspace baseline into docker/steamos-baseline.env, so the test sim can be
# pinned to the device instead of guessing at it.
#
#   scripts/sim/capture-deck-baseline.sh [--print]
#
# WHY THIS EXISTS. The sim's base used to be `FROM archlinux:latest`, under a comment reading "Arch
# base — honouring 'SteamOS is Arch-based'". That is true and it is not enough: archlinux:latest is a
# ROLLING release that drifts continuously ahead of SteamOS 3.x, which is a FROZEN Arch snapshot plus
# Valve's holo/jupiter packages. So `ok - launcher builds + L0 green on Arch` proved the launcher
# builds against tomorrow's glibc/gcc/libsystemd, not against the Deck's — measured, GCC 16 / glibc
# 2.43 in the sim vs GCC 15.1.1 / glibc 2.41 on the device. The sentence was honest and read far
# stronger than it was: the same family of defect as `just power` reporting `mean 0.00 W ... PASS`
# off a missing battery node. A check that answers a different question than the one you asked is not
# a check. docker/steamos.Dockerfile now pins to what this script captures.
#
# THE RULE THIS FOLLOWS. We do not hardcode Valve's mirror URLs or branch names from memory. The Deck
# knows which repos it tracks — /etc/pacman.conf and /etc/pacman.d/*mirrorlist* are the authority —
# so we read them off the unit. When SteamOS updates, re-run this: the diff IS the upgrade note.
#
# WHAT THIS DOES NOT BUY. Matching userspace makes the BUILD and D-BUS layers faithful. It does not
# conjure a GPU, VA-API, gamescope, a battery or ACPI. scripts/sim/run.sh must keep refusing the
# hardware gates with exit 6, and this script exists to make the sim honest, never to widen its
# claims. See .internal/findings/durable/test-sim.md.
#
# Exit (harness §1): 0 ok · 3 env (no Deck configured) · 4 transport (Deck unreachable).
set -euo pipefail
# shellcheck source=scripts/lib.sh
. "$(dirname "$0")/../lib.sh"

OUT="docker/steamos-baseline.env"
print_only=0
[ "${1:-}" = "--print" ] && print_only=1

require_deck

info "capturing baseline from $DECK_HOST ..."

# One SSH round trip: ask the Deck everything at once. Missing values come back empty rather than
# failing the run — an absent key is data ("this unit has no such package"), and the consumer decides
# whether that is fatal.
raw="$(
  deck_ssh "$DECK_HOST" 'bash -s' <<'REMOTE'
set -u
emit() { printf '%s=%s\n' "$1" "${2:-}"; }

# --- identity -------------------------------------------------------------------------------------
. /etc/os-release 2>/dev/null || true
emit OS_ID "${ID:-}"
emit OS_NAME "${NAME:-}"
emit OS_VERSION_ID "${VERSION_ID:-}"
emit OS_BUILD_ID "${BUILD_ID:-}"
emit OS_VARIANT_ID "${VARIANT_ID:-}"
emit KERNEL "$(uname -r 2>/dev/null)"
emit ARCH "$(uname -m 2>/dev/null)"

# --- the unit ("which Deck is this?" — every hardware result so far is OLED-only) ------------------
emit BOARD "$(cat /sys/class/dmi/id/product_name 2>/dev/null)"
emit BOARD_VERSION "$(cat /sys/class/dmi/id/product_version 2>/dev/null)"

# --- the toolchain the launcher must match --------------------------------------------------------
emit GLIBC "$(ldd --version 2>/dev/null | head -1 | awk '{print $NF}')"
emit GCC "$(gcc -dumpfullversion 2>/dev/null || gcc -dumpversion 2>/dev/null)"

# --- the libraries the launcher links (CMake: systemd/curl/pulse/xcb; evdev is read raw) -----------
for p in glibc gcc-libs systemd-libs curl libpulse libxcb libevdev flatpak bubblewrap mesa; do
  v="$(pacman -Q "$p" 2>/dev/null | awk '{print $2}')"
  emit "PKG_$(printf '%s' "$p" | tr 'a-z-' 'A-Z_')" "$v"
done

# --- the repos this unit actually tracks: the authority for what the sim base must be --------------
# Printed as a blob rather than parsed here; the host side records it verbatim for review. Guessing
# "holo-3.5" or a mirror URL from memory is exactly what this avoids.
echo "---PACMAN_CONF---"
grep -vE '^\s*(#|$)' /etc/pacman.conf 2>/dev/null || true
echo "---MIRRORLIST---"
for f in /etc/pacman.d/*mirrorlist*; do
  [ -f "$f" ] || continue
  echo "# $f"
  grep -vE '^\s*(#|$)' "$f" 2>/dev/null || true
done
echo "---END---"
REMOTE
)" || die_transport "baseline capture failed over SSH"

# `^[A-Z][A-Za-z0-9_]*=`, not `^[A-Z_]+=`: the latter silently dropped every PKG_* line the Deck
# sent, because a package name can carry digits. A filter that discards data instead of failing is
# the same silent-drop this whole baseline exists to stop.
kv="$(printf '%s\n' "$raw" | sed -n '1,/---PACMAN_CONF---/p' | grep -E '^[A-Z][A-Za-z0-9_]*=' || true)"
repos="$(printf '%s\n' "$raw" | sed -n '/---PACMAN_CONF---/,/---END---/p')"

[ -n "$kv" ] || die_transport "no baseline values came back — is this a SteamOS unit?"

if [ "$print_only" -eq 1 ]; then
  printf '%s\n' "$kv"
  printf '%s\n' "$repos"
  exit "$EX_OK"
fi

mkdir -p "$(dirname "$OUT")"
{
  echo "# GENERATED by scripts/sim/capture-deck-baseline.sh — do not hand-edit."
  echo "#"
  echo "# The REAL Deck's userspace, captured off the device. docker/steamos.Dockerfile pins to this"
  echo "# so the sim builds against the Deck's glibc/gcc/libsystemd rather than archlinux:latest,"
  echo "# which drifts ahead of SteamOS and quietly answers a different question."
  echo "#"
  echo "# RE-RUN THIS AFTER EVERY SteamOS UPDATE. The git diff of this file is the upgrade note:"
  echo "# it names exactly what moved under the launcher, and a changed GLIBC/GCC is a reason to"
  echo "# re-run 'just sim all' before trusting any prior green."
  echo "#"
  echo "# It records ONE unit. Every hardware result in this project so far is from the OLED"
  echo "# (durable/hardware.md); an LCD baseline would legitimately differ and is not captured here."
  echo "#"
  echo "# Coverage is unchanged by this file: no GPU, no VA-API, no gamescope, no battery, no ACPI"
  echo "# in a container, ever. scripts/sim/run.sh still refuses those gates with exit 6."
  printf '%s\n' "$kv"
  echo
  echo "# ---- the repos this unit tracks (verbatim, for review) --------------------------------"
  printf '%s\n' "$repos" | sed 's/^/# /'
} >"$OUT"

info "wrote $OUT"
printf '%s\n' "$kv" | sed 's/^/  /'
info "review the recorded repos in $OUT before pinning docker/steamos.Dockerfile to them."
