#!/usr/bin/env bash
# Git-based quilt flow (doc §15.1). Commit your change inside cobalt/, then export it here.
. "$(dirname "$0")/lib.sh"
require_cobalt_checkout
cmd="${1:-}"
pin="$(deps_pin)"

regen_series() {
  ( cd "$REPO_ROOT/patches" && ls -1 [0-9]*.patch 2>/dev/null > series.tmp
    { echo "# quilt series — applied in order against DEPS.pin ($pin). Regenerated by 'just patch-refresh'.";
      cat series.tmp 2>/dev/null; } > series
    rm -f series.tmp )
}

case "$cmd" in
  new)
    name="${2:?usage: patch.sh new <name>}"
    info "Exporting cobalt/ HEAD commit as a patch named '$name' ..."
    git -C "$COBALT_TREE" format-patch -1 --zero-commit --no-signature \
      --start-number "$(($(ls patches/[0-9]*.patch 2>/dev/null | wc -l) + 1))" \
      -o "$REPO_ROOT/patches" HEAD >/dev/null
    # rename the just-created file to include the friendly name
    latest="$(ls -t patches/[0-9]*.patch | head -1)"
    mv "$latest" "${latest%.patch}-${name}.patch"
    regen_series ;;
  refresh)
    info "Re-exporting all patches since $pin ..."
    rm -f patches/[0-9]*.patch
    git -C "$COBALT_TREE" format-patch --zero-commit --no-signature \
      -o "$REPO_ROOT/patches" "$pin"..HEAD >/dev/null
    regen_series ;;
  *)
    die "usage: patch.sh [new <name>|refresh]" ;;
esac
info "patches/series updated."
